#ifndef MALE_MUSCLED_H
#define MALE_MUSCLED_H

#define male_muscled_model "rom:/models/male_muscled.t3dm"
#define micey_model "rom:/models/micey.t3dm"
#define gorilla_model "rom:/models/gorilla.t3dm"
#define girl_model "rom:/models/girl.t3dm"

// motion settings

#define MALE_MUSCLED_IDLE_ACCELERATION_RATE 8.0f
#define MALE_MUSCLED_WALK_ACCELERATION_RATE 3.0f
#define MALE_MUSCLED_RUN_ACCELERATION_RATE 5.0f
#define MALE_MUSCLED_SPRINT_ACCELERATION_RATE 8.0f
#define MALE_MUSCLED_ROLL_ACCELERATION_GRIP_RATE 2.0f

#define MALE_MUSCLED_JUMP_ACCELERATION_RATE 50.0f
#define MALE_MUSCLED_AERIAL_CONTROL_RATE 0.5f

#define MALE_MUSCLED_WALK_TARGET_SPEED 185.0f
#define MALE_MUSCLED_RUN_TARGET_SPEED 390.0f
#define MALE_MUSCLED_SPRINT_TARGET_SPEED 520.0f

#define MALE_MUSCLED_JUMP_FORCE_MULTIPLIER 3000
#define MALE_MUSCLED_JUMP_MINIMUM_SPEED 400


// convertion ratio between locomotion animation lenghts

#define MALE_MUSCLED_RUN_TO_WALK_RATIO 1.347826f
#define MALE_MUSCLED_WALK_TO_RUN_RATIO 0.741935f

#define MALE_MUSCLED_SPRINT_TO_RUN_RATIO 1.15f
#define MALE_MUSCLED_RUN_TO_SPRINT_RATIO 0.869565f

#define MALE_MUSCLED_SPRINT_TO_WALK_RATIO 1.55f
#define MALE_MUSCLED_WALK_TO_SPRINT_RATIO 0.645161f


// animation lenghts in seconds

#define MALE_MUSCLED_ACTION_IDLE_MAX_BLENDING_RATIO 0.85f

#define MALE_MUSCLED_WALKING_ANIM_LENGTH 1.033333f
#define MALE_MUSCLED_WALKING_ANIM_LENGTH_HALF 0.516666f

#define MALE_MUSCLED_RUNNING_ANIM_LENGTH_HALF 0.4f
#define MALE_MUSCLED_RUNNING_ANIM_LENGTH 0.766666f

#define MALE_MUSCLED_SPRINTING_ANIM_LENGTH 0.666666f
#define MALE_MUSCLED_SPRINTING_ANIM_LENGTH_HALF 0.333333f

#define MALE_MUSCLED_RUN_TO_ROLLING_ANIM_GROUND 0.3f
#define MALE_MUSCLED_RUN_TO_ROLLING_ANIM_GRIP 0.9f
#define MALE_MUSCLED_RUN_TO_ROLLING_ANIM_STAND 0.9f
#define MALE_MUSCLED_RUN_TO_ROLLING_ANIM_LENGHT 1.166666f

#define MALE_MUSCLED_STAND_TO_ROLLING_ANIM_GRIP 1.433333f
#define MALE_MUSCLED_STAND_TO_ROLLING_ANIM_LENGHT 2.066666f

#define MALE_MUSCLED_JUMP_ANIM_LENGTH 0.633333f
#define MALE_MUSCLED_JUMP_ANIM_CROUCH 0.1f
#define MALE_MUSCLED_JUMP_ANIM_AIR 0.233333f
#define MALE_MUSCLED_JUMP_MAX_BLENDING_RATIO 0.7f
#define MALE_MUSCLED_JUMP_FOOTING_SPEED 0.5f

#define MALE_MUSCLED_LAND_ANIM_LENGTH 0.9f
#define MALE_MUSCLED_LAND_ANIM_GROUND 0.266666f
#define MALE_MUSCLED_LAND_ANIM_STAND 0.833333f


extern ActorMotionSettings male_muscled_motion_settings;

extern ActorAnimationSettings male_muscled_animation_settings;

#endif